import type { BilvisionVehicleData } from "./types";

/**
 * Extended mock vehicle database for development.
 * Covers common Swedish car brands and realistic data.
 * When BILVISION_API_KEY is set, real API data is used instead.
 */
const MOCK_VEHICLES: Record<string, BilvisionVehicleData> = {
  ABC123: {
    regNr:               "ABC123",
    vin:                 "YV1XZ5345F1234567",
    brand:               "Volvo",
    model:               "V70",
    modelYear:           2015,
    color:               "Svart",
    colorCode:           "0AB",
    fuelType:            "diesel",
    engineSizeCC:        1969,
    powerKw:             140,
    transmission:        "automat",
    driveType:           "framhjulsdrift",
    firstRegisteredAt:   "2015-03-15",
    taxClass:            "personbil",
    inspectionValidUntil: "2026-03-31",
    currentOwnerSince:   "2020-06-01",
    insuranceCompany:    "Folksam",
    _rawResponse:        { source: "mock" },
  },
  DEF456: {
    regNr:               "DEF456",
    vin:                 "WBA5A5C59ED123456",
    brand:               "BMW",
    model:               "320d",
    modelYear:           2019,
    color:               "Vit",
    colorCode:           "300",
    fuelType:            "diesel",
    engineSizeCC:        1995,
    powerKw:             140,
    transmission:        "automat",
    driveType:           "bakhjulsdrift",
    firstRegisteredAt:   "2019-05-10",
    taxClass:            "personbil",
    inspectionValidUntil: "2025-05-31",
    currentOwnerSince:   "2022-01-15",
    insuranceCompany:    "If",
    _rawResponse:        { source: "mock" },
  },
  GHI789: {
    regNr:               "GHI789",
    vin:                 "WAUZZZ8K7DA123456",
    brand:               "Audi",
    model:               "A4 Avant",
    modelYear:           2013,
    color:               "Grå",
    colorCode:           "6Y",
    fuelType:            "bensin",
    engineSizeCC:        1984,
    powerKw:             132,
    transmission:        "manuell",
    driveType:           "framhjulsdrift",
    firstRegisteredAt:   "2013-08-22",
    taxClass:            "personbil",
    inspectionValidUntil: "2025-08-31",
    currentOwnerSince:   "2018-03-10",
    insuranceCompany:    "Trygg-Hansa",
    _rawResponse:        { source: "mock" },
  },
  JKL012: {
    regNr:               "JKL012",
    vin:                 "WVWZZZ3CZWE456789",
    brand:               "Volkswagen",
    model:               "Golf",
    modelYear:           2021,
    color:               "Blå",
    colorCode:           "5K",
    fuelType:            "bensin",
    engineSizeCC:        1498,
    powerKw:             110,
    transmission:        "automat",
    driveType:           "framhjulsdrift",
    firstRegisteredAt:   "2021-02-14",
    taxClass:            "personbil",
    inspectionValidUntil: "2027-02-28",
    currentOwnerSince:   "2021-02-14",
    insuranceCompany:    "Länsförsäkringar",
    _rawResponse:        { source: "mock" },
  },
  MNO345: {
    regNr:               "MNO345",
    vin:                 "WMEEJ9AA5KK789012",
    brand:               "Toyota",
    model:               "RAV4",
    modelYear:           2020,
    color:               "Silver",
    colorCode:           "1F7",
    fuelType:            "hybrid",
    engineSizeCC:        2487,
    powerKw:             163,
    transmission:        "automat",
    driveType:           "fyrhjulsdrift",
    firstRegisteredAt:   "2020-09-20",
    taxClass:            "personbil",
    inspectionValidUntil: "2026-09-30",
    currentOwnerSince:   "2020-09-20",
    insuranceCompany:    "Folksam",
    _rawResponse:        { source: "mock" },
  },
  PQR678: {
    regNr:               "PQR678",
    vin:                 "5YJSA1E26MF234567",
    brand:               "Tesla",
    model:               "Model 3",
    modelYear:           2022,
    color:               "Vit",
    colorCode:           "PPSW",
    fuelType:            "el",
    engineSizeCC:        null,
    powerKw:             239,
    transmission:        "automat",
    driveType:           "bakhjulsdrift",
    firstRegisteredAt:   "2022-04-01",
    taxClass:            "personbil",
    inspectionValidUntil: "2028-04-30",
    currentOwnerSince:   "2022-04-01",
    insuranceCompany:    "If",
    _rawResponse:        { source: "mock" },
  },
  STU901: {
    regNr:               "STU901",
    vin:                 "W0L000000Y2345678",
    brand:               "Kia",
    model:               "Niro PHEV",
    modelYear:           2023,
    color:               "Grön",
    colorCode:           "DWG",
    fuelType:            "laddhybrid",
    engineSizeCC:        1580,
    powerKw:             104,
    transmission:        "automat",
    driveType:           "framhjulsdrift",
    firstRegisteredAt:   "2023-06-15",
    taxClass:            "personbil",
    inspectionValidUntil: "2029-06-30",
    currentOwnerSince:   "2023-06-15",
    insuranceCompany:    "Trygg-Hansa",
    _rawResponse:        { source: "mock" },
  },
  VXY234: {
    regNr:               "VXY234",
    vin:                 "YS2R4X20009876543",
    brand:               "Scania",
    model:               "R450",
    modelYear:           2018,
    color:               "Vit",
    colorCode:           null,
    fuelType:            "diesel",
    engineSizeCC:        12742,
    powerKw:             331,
    transmission:        "automat",
    driveType:           "bakhjulsdrift",
    firstRegisteredAt:   "2018-01-10",
    taxClass:            "lastbil",
    inspectionValidUntil: "2026-01-31",
    currentOwnerSince:   "2018-01-10",
    insuranceCompany:    "Moderna Försäkringar",
    _rawResponse:        { source: "mock" },
  },
  TRJ620: {
    regNr:               "TRJ620",
    vin:                 "WBA2J1105KB123456",
    brand:               "BMW",
    model:               "M240i",
    modelYear:           2019,
    color:               null,
    colorCode:           null,
    fuelType:            "bensin",
    engineSizeCC:        2998,
    powerKw:             250,
    transmission:        "automat",
    driveType:           "bakhjulsdrift",
    firstRegisteredAt:   "2019-01-01",
    taxClass:            "personbil",
    inspectionValidUntil: "2026-01-31",
    currentOwnerSince:   null,
    insuranceCompany:    null,
    _rawResponse:        { source: "mock" },
  },
};

/**
 * Returns mock vehicle data for development.
 * Simulates realistic API latency.
 */
export async function getMockVehicle(
  regNr: string,
): Promise<BilvisionVehicleData | null> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  return MOCK_VEHICLES[regNr.toUpperCase()] ?? null;
}
